# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ "3.8", "3.9", "3.10" ]

    env:
      OS: ${{ matrix.os }}
      USING_COVERAGE: '3.8,3.9,3.10'


    steps:
      - uses: "actions/checkout@v3"
      - name: Setup Python
        uses: "actions/setup-python@v3"
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Install dependencies
        run: |
          set -xe
          python -VV
          python -m site
          python -m pip install --upgrade pip
          if [ -f requirements_test.txt ]; then pip install -r requirements_test.txt; fi
      - name: "Run tox targets for ${{ matrix.python-version }} on ${{ matrix.os }}"
        run: "python -m tox"

      - name: "Upload coverage to Codecov"
        if: "contains(env.USING_COVERAGE, matrix.python-version)"
        uses: "codecov/codecov-action@v3"
        with:
          file: ./coverage.xml
          files: ./coverage1.xml,./coverage2.xml
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true
